server:
  port: 8082

rest:
  api: api/v1/payments

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration